
import tkinter as tk
import color.wombat

sticky_all = (tk.N, tk.S, tk.E, tk.W)

APP_HEIGHT = 1000
APP_WIDTH = 1000

APP_MIN_HEIGHT = 800
APP_MIN_WIDTH = 800

COLOR_NORMAL  = color.wombat.white
COLOR_COPY    = color.wombat.green
COLOR_CLEAN   = color.wombat.red
COLOR_CARD    = color.wombat.black
COLOR_PADDING = color.wombat.grayDark

CARD_PADDING_X = 8
CARD_PADDING_Y = 10
CARD_BAR_WIDTH = 10
CARD_HBAR_WIDTH = 5

CARD_TITLE_PADDING = 20
CARD_TITLE_FONT = "DejaVu Sans Mono"
CARD_TITLE_SIZE = 16

CARD_OUTPUT_TITLE_PADDING = 10
CARD_OUTPUT_TITLE_FONT = "DejaVu Sans Mono"
CARD_OUTPUT_TITLE_SIZE = 12

CARD_OUTPUT_PADDING_X = 6
CARD_OUTPUT_PADDING_Y = 6
CARD_OUTPUT_FONT = "DejaVu Sans Mono"
CARD_OUTPUT_SIZE = 10



BUTTONBAR_FRAME_PADX_INNER = 5
BUTTONBAR_FRAME_PADY_INNER = 5
BUTTONBAR_FRAME_PADX_OUTTER = 10
BUTTONBAR_FRAME_PADY_OUTTER = 5

BUTTONBAR_BUTTON_PADX = 5
BUTTONBAR_BUTTON_FONT = "DejaVu Sans"
BUTTONBAR_BUTTON_SIZE = 10




TREE_HEADING_FONT = "DejaVu Sans" 
TREE_HEADING_SIZE = 12
TREE_FONT = "DejaVu Sans Mono" 
TREE_SIZE = 10

TREE_NAME_WIDTH = 250

